In [ ]:
def get_interactors(dict):   #to go through the dictionary and rearrange the data into a dataframe
    import pandas as pd
    import numpy as np
    interactome_all = {}
    interactome_bi = {}
    index = {'CSNK1A1': '1452', 'CSNK1A1L': '122011', 'CSNK1D': '1453', 'CSNK1E': '1454'}
    all_methods= ['Two-hybrid','PCA','Co-fractionation', 'Biochemical Activity',  'Protein-RNA', 'Affinity Capture-Luminescence', 'Far Western', 'Reconstituted Complex', 'Affinity Capture-Western', 'Co-crystal Structure', 'Co-purification', 'Proximity Label-MS', 'Protein-peptide', 'Co-localization', 'Affinity Capture-RNA',  'Affinity Capture-MS', 'FRET']
    binary_methods = ["Two-hybrid",'PCA', 'Biochemical Activity', 'Affinity Capture-Luminescence', 'Reconstituted Complex', 'Co-crystal Structure', 'FRET']
    for protein in dict.keys():
        interactome_all[protein] = {}
        interactome_bi[protein] = {}
        for bait1, prey1 in dict[protein].items():
            if protein != 'HRR25':
                proteinid = index[protein]
            else:
                proteinid = protein
            if bait1 == proteinid:
                for bait2, prey2 in prey1.items():
                    count1 = 0
                    count2 = 0
                    for bait3,prey3 in prey2.items():
                        count1 = prey3 + count1
                        if bait3 in binary_methods:
                            count2 = prey3 + count2
                    try: 
                        interactome_all[protein][bait2] += count1
                    except KeyError:
                        interactome_all[protein][bait2] = count1

                    try: 
                        interactome_bi[protein][bait2] += count2
                    except KeyError:
                        interactome_bi[protein][bait2] = count2
            else:
                for bait2, prey2 in prey1.items():
                    count3=0
                    count4=0
                    for bait3, prey3 in prey2.items():
                        count3 = prey3 + count3
                        if bait3 in binary_methods:
                            count4 = prey3 + count4
                    try: 
                        interactome_all[protein][bait1] += count3
                    except KeyError:
                        interactome_all[protein][bait1] = count3

                    try: 
                        interactome_bi[protein][bait1] += count4
                    except KeyError:
                        interactome_bi[protein][bait1] = count4
    df1 = pd.DataFrame.from_dict(interactome_all)
    df2 = pd.DataFrame.from_dict(interactome_bi)
    df1 = df1.replace(np.nan, 0)
    df2 = df2.replace(np.nan, 0)
    return(df1, df2)

In [5]:
def get_data(dir):   #to go through the data folder and fetch the data in a big dictionary
    import json
    import os
    database = {}
    for filename in os.listdir(dir):
        dicti = {}
        f = os.path.join(dir, filename)
        with open (f) as s:
            data = s.read()
            data = data.replace('\'', '\"')
            dicti = json.loads(data)
            name = filename.split('.')[0]
            database[name] = dicti['ij']        
    print(list(database.keys()))
    return database

In [10]:
import pandas as pd
import numpy as np
dir = 'biogrid_data'
database = get_data(dir)
interactome_all = pd.DataFrame(columns=('Interactors', 'CSKN1A1','CSNK1A1L', 'CSNK1E', 'CSNK1D'))
interactome_bi = pd.DataFrame(columns=('Interactors', 'CSKN1A1','CSNK1A1L', 'CSNK1E', 'CSNK1D'))
index = {'CSNK1A1': '1452', 'CSNK1A1L': '122011', 'CSNK1D': '1453', 'CSNK1E': '1454'}
all_methods= ['Two-hybrid','PCA','Co-fractionation', 'Biochemical Activity',  'Protein-RNA', 'Affinity Capture-Luminescence', 'Far Western', 'Reconstituted Complex', 'Affinity Capture-Western', 'Co-crystal Structure', 'Co-purification', 'Proximity Label-MS', 'Protein-peptide', 'Co-localization', 'Affinity Capture-RNA',  'Affinity Capture-MS', 'FRET']
binary_methods = ["Two-hybrid",'PCA', 'Biochemical Activity', 'Affinity Capture-Luminescence', 'Reconstituted Complex', 'Co-crystal Structure', 'FRET']
entrez_id = pd.read_csv('entrez_id.csv')

['CSNK1A1', 'CSNK1E', 'CSNK1D', 'CSNK1A1L']

In [19]:
for gene in database.keys():
    outgeneid = int(entrez_id['ID'][entrez_id['Symbol']==gene])
    for bait1, prey1 in database[gene].items():
        print (bait1)
        #intgeneid = entrez_id['Symbol'][entrez_id['ID']==bait1]
        for bait2, prey2

10010
Series([], Name: Symbol, dtype: object)
100506658
Series([], Name: Symbol, dtype: object)
10112
Series([], Name: Symbol, dtype: object)
102724631
Series([], Name: Symbol, dtype: object)
10410
Series([], Name: Symbol, dtype: object)
10450
Series([], Name: Symbol, dtype: object)
10484
Series([], Name: Symbol, dtype: object)
10551
Series([], Name: Symbol, dtype: object)
10892
Series([], Name: Symbol, dtype: object)
10987
Series([], Name: Symbol, dtype: object)
11033
Series([], Name: Symbol, dtype: object)
11052
Series([], Name: Symbol, dtype: object)
11091
Series([], Name: Symbol, dtype: object)
112399
Series([], Name: Symbol, dtype: object)
1131
Series([], Name: Symbol, dtype: object)
116143
Series([], Name: Symbol, dtype: object)
1213
Series([], Name: Symbol, dtype: object)
122011
Series([], Name: Symbol, dtype: object)
124245
Series([], Name: Symbol, dtype: object)
128866
Series([], Name: Symbol, dtype: object)
1314
Series([], Name: Symbol, dtype: object)
132724
Series([], Name: Symbol, dtype: object)
135398
Series([], Name: Symbol, dtype: object)
136263
Series([], Name: Symbol, dtype: object)
140735
Series([], Name: Symbol, dtype: object)
1432
Series([], Name: Symbol, dtype: object)
1452
Series([], Name: Symbol, dtype: object)
145508
Series([], Name: Symbol, dtype: object)
1499
Series([], Name: Symbol, dtype: object)
161176
Series([], Name: Symbol, dtype: object)
1803
Series([], Name: Symbol, dtype: object)
1869
Series([], Name: Symbol, dtype: object)
1894
Series([], Name: Symbol, dtype: object)
1956
Series([], Name: Symbol, dtype: object)
1994
Series([], Name: Symbol, dtype: object)
2010
Series([], Name: Symbol, dtype: object)
2099
Series([], Name: Symbol, dtype: object)
2100
Series([], Name: Symbol, dtype: object)
221150
Series([], Name: Symbol, dtype: object)
22927
Series([], Name: Symbol, dtype: object)
22981
Series([], Name: Symbol, dtype: object)
23235
Series([], Name: Symbol, dtype: object)
23476
Series([], Name: Symbol, dtype: object)
23586
Series([], Name: Symbol, dtype: object)
2512
Series([], Name: Symbol, dtype: object)
2547
Series([], Name: Symbol, dtype: object)
26135
Series([], Name: Symbol, dtype: object)
26471
Series([], Name: Symbol, dtype: object)
284680
Series([], Name: Symbol, dtype: object)
286077
Series([], Name: Symbol, dtype: object)
28966
Series([], Name: Symbol, dtype: object)
30011
Series([], Name: Symbol, dtype: object)
3169
Series([], Name: Symbol, dtype: object)
3191
Series([], Name: Symbol, dtype: object)
3320
Series([], Name: Symbol, dtype: object)
340069
Series([], Name: Symbol, dtype: object)
3630
Series([], Name: Symbol, dtype: object)
3667
Series([], Name: Symbol, dtype: object)
3676
Series([], Name: Symbol, dtype: object)
3845
Series([], Name: Symbol, dtype: object)
387893
Series([], Name: Symbol, dtype: object)
388
Series([], Name: Symbol, dtype: object)
388468
Series([], Name: Symbol, dtype: object)
3916
Series([], Name: Symbol, dtype: object)
399687
Series([], Name: Symbol, dtype: object)
4193
Series([], Name: Symbol, dtype: object)
4194
Series([], Name: Symbol, dtype: object)
474
Series([], Name: Symbol, dtype: object)
4772
Series([], Name: Symbol, dtype: object)
4775
Series([], Name: Symbol, dtype: object)
4792
Series([], Name: Symbol, dtype: object)
4914
Series([], Name: Symbol, dtype: object)
5108
Series([], Name: Symbol, dtype: object)
51185
Series([], Name: Symbol, dtype: object)
51199
Series([], Name: Symbol, dtype: object)
51343
Series([], Name: Symbol, dtype: object)
51368
Series([], Name: Symbol, dtype: object)
51512
Series([], Name: Symbol, dtype: object)
51517
Series([], Name: Symbol, dtype: object)
5347
Series([], Name: Symbol, dtype: object)
53615
Series([], Name: Symbol, dtype: object)
54101
Series([], Name: Symbol, dtype: object)
54443
Series([], Name: Symbol, dtype: object)
54894
Series([], Name: Symbol, dtype: object)
55004
Series([], Name: Symbol, dtype: object)
5501
Series([], Name: Symbol, dtype: object)
55054
Series([], Name: Symbol, dtype: object)
55294
Series([], Name: Symbol, dtype: object)
55667
Series([], Name: Symbol, dtype: object)
55737
Series([], Name: Symbol, dtype: object)
5587
Series([], Name: Symbol, dtype: object)
56649
Series([], Name: Symbol, dtype: object)
5727
Series([], Name: Symbol, dtype: object)
5728
Series([], Name: Symbol, dtype: object)
57407
Series([], Name: Symbol, dtype: object)
5829
Series([], Name: Symbol, dtype: object)
58504
Series([], Name: Symbol, dtype: object)
6117
Series([], Name: Symbol, dtype: object)
6118
Series([], Name: Symbol, dtype: object)
6119
Series([], Name: Symbol, dtype: object)
613
Series([], Name: Symbol, dtype: object)
6597
Series([], Name: Symbol, dtype: object)
65992
Series([], Name: Symbol, dtype: object)
6657
Series([], Name: Symbol, dtype: object)
6928
Series([], Name: Symbol, dtype: object)
7074
Series([], Name: Symbol, dtype: object)
7133
Series([], Name: Symbol, dtype: object)
7157
Series([], Name: Symbol, dtype: object)
7186
Series([], Name: Symbol, dtype: object)
7405
Series([], Name: Symbol, dtype: object)
7412
Series([], Name: Symbol, dtype: object)
7465
Series([], Name: Symbol, dtype: object)
7514
Series([], Name: Symbol, dtype: object)
7531
Series([], Name: Symbol, dtype: object)
7532
Series([], Name: Symbol, dtype: object)
7706
Series([], Name: Symbol, dtype: object)
7764
Series([], Name: Symbol, dtype: object)
79007
Series([], Name: Symbol, dtype: object)
79927
Series([], Name: Symbol, dtype: object)
81610
Series([], Name: Symbol, dtype: object)
81631
Series([], Name: Symbol, dtype: object)
8312
Series([], Name: Symbol, dtype: object)
84433
Series([], Name: Symbol, dtype: object)
84445
Series([], Name: Symbol, dtype: object)
8517
Series([], Name: Symbol, dtype: object)
8519
Series([], Name: Symbol, dtype: object)
8715
Series([], Name: Symbol, dtype: object)
8772
Series([], Name: Symbol, dtype: object)
8829
Series([], Name: Symbol, dtype: object)
8844
Series([], Name: Symbol, dtype: object)
8940
Series([], Name: Symbol, dtype: object)
8945
Series([], Name: Symbol, dtype: object)
9110
Series([], Name: Symbol, dtype: object)
9343
Series([], Name: Symbol, dtype: object)
94274
Series([], Name: Symbol, dtype: object)
9493
Series([], Name: Symbol, dtype: object)
9662
Series([], Name: Symbol, dtype: object)
9859
Series([], Name: Symbol, dtype: object)
9919
Series([], Name: Symbol, dtype: object)
9928
Series([], Name: Symbol, dtype: object)
9958
Series([], Name: Symbol, dtype: object)
9968
Series([], Name: Symbol, dtype: object)
999
Series([], Name: Symbol, dtype: object)
100506144
Series([], Name: Symbol, dtype: object)
100506658
Series([], Name: Symbol, dtype: object)
10130
Series([], Name: Symbol, dtype: object)
10189
Series([], Name: Symbol, dtype: object)
10369
Series([], Name: Symbol, dtype: object)
10403
Series([], Name: Symbol, dtype: object)
10458
Series([], Name: Symbol, dtype: object)
10612
Series([], Name: Symbol, dtype: object)
10713
Series([], Name: Symbol, dtype: object)
10970
Series([], Name: Symbol, dtype: object)
11014
Series([], Name: Symbol, dtype: object)
11051
Series([], Name: Symbol, dtype: object)
11170
Series([], Name: Symbol, dtype: object)
11325
Series([], Name: Symbol, dtype: object)
114991
Series([], Name: Symbol, dtype: object)
116442
Series([], Name: Symbol, dtype: object)
1213
Series([], Name: Symbol, dtype: object)
124245
Series([], Name: Symbol, dtype: object)
129804
Series([], Name: Symbol, dtype: object)
136263
Series([], Name: Symbol, dtype: object)
1407
Series([], Name: Symbol, dtype: object)
1452
Series([], Name: Symbol, dtype: object)
1454
Series([], Name: Symbol, dtype: object)
145508
Series([], Name: Symbol, dtype: object)
1500
Series([], Name: Symbol, dtype: object)
151246
Series([], Name: Symbol, dtype: object)
154743
Series([], Name: Symbol, dtype: object)
157753
Series([], Name: Symbol, dtype: object)
166
Series([], Name: Symbol, dtype: object)
1856
Series([], Name: Symbol, dtype: object)
1857
Series([], Name: Symbol, dtype: object)
1994
Series([], Name: Symbol, dtype: object)
200150
Series([], Name: Symbol, dtype: object)
2017
Series([], Name: Symbol, dtype: object)
221154
Series([], Name: Symbol, dtype: object)
22832
Series([], Name: Symbol, dtype: object)
22861
Series([], Name: Symbol, dtype: object)
22881
Series([], Name: Symbol, dtype: object)
23092
Series([], Name: Symbol, dtype: object)
23175
Series([], Name: Symbol, dtype: object)
23192
Series([], Name: Symbol, dtype: object)
23286
Series([], Name: Symbol, dtype: object)
23299
Series([], Name: Symbol, dtype: object)
23586
Series([], Name: Symbol, dtype: object)
23770
Series([], Name: Symbol, dtype: object)
2512
Series([], Name: Symbol, dtype: object)
25793
Series([], Name: Symbol, dtype: object)
26043
Series([], Name: Symbol, dtype: object)
266971
Series([], Name: Symbol, dtype: object)
27091
Series([], Name: Symbol, dtype: object)
27092
Series([], Name: Symbol, dtype: object)
27338
Series([], Name: Symbol, dtype: object)
284996
Series([], Name: Symbol, dtype: object)
286077
Series([], Name: Symbol, dtype: object)
29100
Series([], Name: Symbol, dtype: object)
29896
Series([], Name: Symbol, dtype: object)
324
Series([], Name: Symbol, dtype: object)
330
Series([], Name: Symbol, dtype: object)
351
Series([], Name: Symbol, dtype: object)
3638
Series([], Name: Symbol, dtype: object)
3718
Series([], Name: Symbol, dtype: object)
3739
Series([], Name: Symbol, dtype: object)
3796
Series([], Name: Symbol, dtype: object)
4043
Series([], Name: Symbol, dtype: object)
4055
Series([], Name: Symbol, dtype: object)
406
Series([], Name: Symbol, dtype: object)
4077
Series([], Name: Symbol, dtype: object)
4163
Series([], Name: Symbol, dtype: object)
474
Series([], Name: Symbol, dtype: object)
4799
Series([], Name: Symbol, dtype: object)
4914
Series([], Name: Symbol, dtype: object)
494119
Series([], Name: Symbol, dtype: object)
51073
Series([], Name: Symbol, dtype: object)
5108
Series([], Name: Symbol, dtype: object)
5110
Series([], Name: Symbol, dtype: object)
51141
Series([], Name: Symbol, dtype: object)
51204
Series([], Name: Symbol, dtype: object)
51233
Series([], Name: Symbol, dtype: object)
51368
Series([], Name: Symbol, dtype: object)
51490
Series([], Name: Symbol, dtype: object)
51512
Series([], Name: Symbol, dtype: object)
5170
Series([], Name: Symbol, dtype: object)
5187
Series([], Name: Symbol, dtype: object)
5305
Series([], Name: Symbol, dtype: object)
54101
Series([], Name: Symbol, dtype: object)
54509
Series([], Name: Symbol, dtype: object)
54819
Series([], Name: Symbol, dtype: object)
54851
Series([], Name: Symbol, dtype: object)
54888
Series([], Name: Symbol, dtype: object)
54894
Series([], Name: Symbol, dtype: object)
5499
Series([], Name: Symbol, dtype: object)
5514
Series([], Name: Symbol, dtype: object)
55177
Series([], Name: Symbol, dtype: object)
55217
Series([], Name: Symbol, dtype: object)
55319
Series([], Name: Symbol, dtype: object)
55646
Series([], Name: Symbol, dtype: object)
5566
Series([], Name: Symbol, dtype: object)
55861
Series([], Name: Symbol, dtype: object)
56001
Series([], Name: Symbol, dtype: object)
5601
Series([], Name: Symbol, dtype: object)
56902
Series([], Name: Symbol, dtype: object)
5720
Series([], Name: Symbol, dtype: object)
57506
Series([], Name: Symbol, dtype: object)
57584
Series([], Name: Symbol, dtype: object)
5789
Series([], Name: Symbol, dtype: object)
58504
Series([], Name: Symbol, dtype: object)
5978
Series([], Name: Symbol, dtype: object)
60468
Series([], Name: Symbol, dtype: object)
60485
Series([], Name: Symbol, dtype: object)
6102
Series([], Name: Symbol, dtype: object)
6259
Series([], Name: Symbol, dtype: object)
636
Series([], Name: Symbol, dtype: object)
637
Series([], Name: Symbol, dtype: object)
63915
Series([], Name: Symbol, dtype: object)
63943
Series([], Name: Symbol, dtype: object)
6447
Series([], Name: Symbol, dtype: object)
6597
Series([], Name: Symbol, dtype: object)
6602
Series([], Name: Symbol, dtype: object)
6901
Series([], Name: Symbol, dtype: object)
6924
Series([], Name: Symbol, dtype: object)
705
Series([], Name: Symbol, dtype: object)
7074
Series([], Name: Symbol, dtype: object)
7132
Series([], Name: Symbol, dtype: object)
7133
Series([], Name: Symbol, dtype: object)
7157
Series([], Name: Symbol, dtype: object)
7158
Series([], Name: Symbol, dtype: object)
7187
Series([], Name: Symbol, dtype: object)
7289
Series([], Name: Symbol, dtype: object)
7322
Series([], Name: Symbol, dtype: object)
7434
Series([], Name: Symbol, dtype: object)
7514
Series([], Name: Symbol, dtype: object)
753
Series([], Name: Symbol, dtype: object)
760
Series([], Name: Symbol, dtype: object)
79007
Series([], Name: Symbol, dtype: object)
79869
Series([], Name: Symbol, dtype: object)
79927
Series([], Name: Symbol, dtype: object)
80184
Series([], Name: Symbol, dtype: object)
8153
Series([], Name: Symbol, dtype: object)
81559
Series([], Name: Symbol, dtype: object)
8202
Series([], Name: Symbol, dtype: object)
830
Series([], Name: Symbol, dtype: object)
8312
Series([], Name: Symbol, dtype: object)
84254
Series([], Name: Symbol, dtype: object)
84285
Series([], Name: Symbol, dtype: object)
84295
Series([], Name: Symbol, dtype: object)
8449
Series([], Name: Symbol, dtype: object)
84553
Series([], Name: Symbol, dtype: object)
84985
Series([], Name: Symbol, dtype: object)
85395
Series([], Name: Symbol, dtype: object)
8864
Series([], Name: Symbol, dtype: object)
899
Series([], Name: Symbol, dtype: object)
9110
Series([], Name: Symbol, dtype: object)
9128
Series([], Name: Symbol, dtype: object)
9129
Series([], Name: Symbol, dtype: object)
923
Series([], Name: Symbol, dtype: object)
92675
Series([], Name: Symbol, dtype: object)
9353
Series([], Name: Symbol, dtype: object)
93974
Series([], Name: Symbol, dtype: object)
93986
Series([], Name: Symbol, dtype: object)
94134
Series([], Name: Symbol, dtype: object)
94274
Series([], Name: Symbol, dtype: object)
9575
Series([], Name: Symbol, dtype: object)
9616
Series([], Name: Symbol, dtype: object)
9631
Series([], Name: Symbol, dtype: object)
9824
Series([], Name: Symbol, dtype: object)
9928
Series([], Name: Symbol, dtype: object)
10010
Series([], Name: Symbol, dtype: object)
10112
Series([], Name: Symbol, dtype: object)
10133
Series([], Name: Symbol, dtype: object)
10142
Series([], Name: Symbol, dtype: object)
10241
Series([], Name: Symbol, dtype: object)
10369
Series([], Name: Symbol, dtype: object)
10612
Series([], Name: Symbol, dtype: object)
10940
Series([], Name: Symbol, dtype: object)
114836
Series([], Name: Symbol, dtype: object)
135398
Series([], Name: Symbol, dtype: object)
136263
Series([], Name: Symbol, dtype: object)
1452
Series([], Name: Symbol, dtype: object)
1453
Series([], Name: Symbol, dtype: object)
1454
Series([], Name: Symbol, dtype: object)
145508
Series([], Name: Symbol, dtype: object)
157753
Series([], Name: Symbol, dtype: object)
166
Series([], Name: Symbol, dtype: object)
1814
Series([], Name: Symbol, dtype: object)
1856
Series([], Name: Symbol, dtype: object)
2017
Series([], Name: Symbol, dtype: object)
2022
Series([], Name: Symbol, dtype: object)
2146
Series([], Name: Symbol, dtype: object)
221154
Series([], Name: Symbol, dtype: object)
2273
Series([], Name: Symbol, dtype: object)
23092
Series([], Name: Symbol, dtype: object)
23299
Series([], Name: Symbol, dtype: object)
23390
Series([], Name: Symbol, dtype: object)
2353
Series([], Name: Symbol, dtype: object)
23621
Series([], Name: Symbol, dtype: object)
2512
Series([], Name: Symbol, dtype: object)
2697
Series([], Name: Symbol, dtype: object)
27091
Series([], Name: Symbol, dtype: object)
27092
Series([], Name: Symbol, dtype: object)
286077
Series([], Name: Symbol, dtype: object)
29896
Series([], Name: Symbol, dtype: object)
3187
Series([], Name: Symbol, dtype: object)
3191
Series([], Name: Symbol, dtype: object)
324
Series([], Name: Symbol, dtype: object)
328
Series([], Name: Symbol, dtype: object)
3312
Series([], Name: Symbol, dtype: object)
351
Series([], Name: Symbol, dtype: object)
3614
Series([], Name: Symbol, dtype: object)
3831
Series([], Name: Symbol, dtype: object)
387129
Series([], Name: Symbol, dtype: object)
387893
Series([], Name: Symbol, dtype: object)
3921
Series([], Name: Symbol, dtype: object)
4043
Series([], Name: Symbol, dtype: object)
4087
Series([], Name: Symbol, dtype: object)
4088
Series([], Name: Symbol, dtype: object)
4137
Series([], Name: Symbol, dtype: object)
4163
Series([], Name: Symbol, dtype: object)
4193
Series([], Name: Symbol, dtype: object)
472
Series([], Name: Symbol, dtype: object)
4734
Series([], Name: Symbol, dtype: object)
474
Series([], Name: Symbol, dtype: object)
4772
Series([], Name: Symbol, dtype: object)
4773
Series([], Name: Symbol, dtype: object)
50674
Series([], Name: Symbol, dtype: object)
5108
Series([], Name: Symbol, dtype: object)
51233
Series([], Name: Symbol, dtype: object)
51343
Series([], Name: Symbol, dtype: object)
51368
Series([], Name: Symbol, dtype: object)
5170
Series([], Name: Symbol, dtype: object)
5187
Series([], Name: Symbol, dtype: object)
5217
Series([], Name: Symbol, dtype: object)
5371
Series([], Name: Symbol, dtype: object)
54101
Series([], Name: Symbol, dtype: object)
54443
Series([], Name: Symbol, dtype: object)
55177
Series([], Name: Symbol, dtype: object)
55337
Series([], Name: Symbol, dtype: object)
5536
Series([], Name: Symbol, dtype: object)
5537
Series([], Name: Symbol, dtype: object)
55720
Series([], Name: Symbol, dtype: object)
5577
Series([], Name: Symbol, dtype: object)
55861
Series([], Name: Symbol, dtype: object)
56001
Series([], Name: Symbol, dtype: object)
57144
Series([], Name: Symbol, dtype: object)
57154
Series([], Name: Symbol, dtype: object)
57381
Series([], Name: Symbol, dtype: object)
57532
Series([], Name: Symbol, dtype: object)
57584
Series([], Name: Symbol, dtype: object)
57664
Series([], Name: Symbol, dtype: object)
5784
Series([], Name: Symbol, dtype: object)
5789
Series([], Name: Symbol, dtype: object)
58504
Series([], Name: Symbol, dtype: object)
60485
Series([], Name: Symbol, dtype: object)
6102
Series([], Name: Symbol, dtype: object)
64375
Series([], Name: Symbol, dtype: object)
6597
Series([], Name: Symbol, dtype: object)
6622
Series([], Name: Symbol, dtype: object)
672
Series([], Name: Symbol, dtype: object)
705
Series([], Name: Symbol, dtype: object)
7155
Series([], Name: Symbol, dtype: object)
7157
Series([], Name: Symbol, dtype: object)
7514
Series([], Name: Symbol, dtype: object)
753
Series([], Name: Symbol, dtype: object)
7534
Series([], Name: Symbol, dtype: object)
7706
Series([], Name: Symbol, dtype: object)
7813
Series([], Name: Symbol, dtype: object)
7818
Series([], Name: Symbol, dtype: object)
79007
Series([], Name: Symbol, dtype: object)
79155
Series([], Name: Symbol, dtype: object)
79169
Series([], Name: Symbol, dtype: object)
79734
Series([], Name: Symbol, dtype: object)
79760
Series([], Name: Symbol, dtype: object)
79927
Series([], Name: Symbol, dtype: object)
8209
Series([], Name: Symbol, dtype: object)
8312
Series([], Name: Symbol, dtype: object)
832
Series([], Name: Symbol, dtype: object)
84144
Series([], Name: Symbol, dtype: object)
84232
Series([], Name: Symbol, dtype: object)
84445
Series([], Name: Symbol, dtype: object)
84708
Series([], Name: Symbol, dtype: object)
84899
Series([], Name: Symbol, dtype: object)
84950
Series([], Name: Symbol, dtype: object)
8517
Series([], Name: Symbol, dtype: object)
85358
Series([], Name: Symbol, dtype: object)
8772
Series([], Name: Symbol, dtype: object)
8864
Series([], Name: Symbol, dtype: object)
8887
Series([], Name: Symbol, dtype: object)
9110
Series([], Name: Symbol, dtype: object)
9401
Series([], Name: Symbol, dtype: object)
94103
Series([], Name: Symbol, dtype: object)
94274
Series([], Name: Symbol, dtype: object)
9493
Series([], Name: Symbol, dtype: object)
9788
Series([], Name: Symbol, dtype: object)
9928
Series([], Name: Symbol, dtype: object)
999
Series([], Name: Symbol, dtype: object)
10112
Series([], Name: Symbol, dtype: object)
1053
Series([], Name: Symbol, dtype: object)